import type { MenuItem } from "../types";

export const EMOJIS = [
  "☕",
  "🍵",
  "🍊",
  "🧃",
  "🥤",
  "🍺",
  "🧋",
  "🍷",
  "🥗",
  "🥙",
  "🌮",
  "🥪",
  "🍱",
  "🥫",
  "🫔",
  "🧆",
  "🥩",
  "🍖",
  "🍗",
  "🌭",
  "🍔",
  "🍟",
  "🥓",
  "🍣",
  "🍲",
  "🍜",
  "🍝",
  "🥘",
  "🫕",
  "🍛",
  "🥣",
  "🍤",
  "🍮",
  "🍰",
  "🍩",
  "🍪",
  "🧁",
  "🎂",
  "🍫",
  "🍬",
  "🍽️",
  "🌶️",
  "🧀",
  "🥚",
  "🫒",
  "🥑",
  "🍅",
  "🫙",
];

export const INITIAL_MENU: MenuItem[] = [
  { id: "1", name: "Espresso", price: 110, category: "İçecekler", emoji: "☕" },
  {
    id: "2",
    name: "Cappuccino",
    price: 130,
    category: "İçecekler",
    emoji: "☕",
  },
  { id: "3", name: "Türk Çayı", price: 45, category: "İçecekler", emoji: "🍵" },
  { id: "4", name: "Taze OJ", price: 85, category: "İçecekler", emoji: "🍊" },
  {
    id: "5",
    name: "Sezar Salata",
    price: 195,
    category: "Salatalar",
    emoji: "🥗",
  },
  {
    id: "6",
    name: "Akdeniz Salata",
    price: 175,
    category: "Salatalar",
    emoji: "🥗",
  },
  {
    id: "7",
    name: "Izgara Köfte",
    price: 285,
    category: "Izgara",
    emoji: "🥩",
  },
  {
    id: "8",
    name: "Kuzu Pirzola",
    price: 420,
    category: "Izgara",
    emoji: "🍖",
  },
  { id: "9", name: "Tavuk Şiş", price: 265, category: "Izgara", emoji: "🍗" },
  {
    id: "10",
    name: "Mercimek Çorbası",
    price: 95,
    category: "Çorbalar",
    emoji: "🍲",
  },
  {
    id: "11",
    name: "Domates Çorbası",
    price: 90,
    category: "Çorbalar",
    emoji: "🍅",
  },
  {
    id: "12",
    name: "Kazandibi",
    price: 120,
    category: "Tatlılar",
    emoji: "🍮",
  },
  { id: "13", name: "Sütlaç", price: 110, category: "Tatlılar", emoji: "🍚" },
  {
    id: "14",
    name: "Adana Kebap",
    price: 320,
    category: "Ana Yemekler",
    emoji: "🌶️",
  },
  {
    id: "15",
    name: "Karışık Kebap",
    price: 380,
    category: "Ana Yemekler",
    emoji: "🍽️",
  },
];
